### ISSUE TITLE
APTweaks tick change keeps showing up in log

### ISSUE THREAD

**Issue by BugmanBugman** [MarkusBordihn/adaptive_performance_tweaks#1]
**Describe the bug**
Title. I'm not sure if this is intentional or not, but i can see it getting annoying during gameplay

**To Reproduce**
1. start a world with APTweaks2
2. play long enough til it starts changing gamerules
3.  notice how the logs keep showing up in chat
4. 
**Expected behavior**
for it to happen in debug logs only

**Screenshots**
![2021-03-04_16 29 14](https://user-images.githubusercontent.com/40730042/110225237-29281e80-7ea9-11eb-9bfc-67278ce50721.png)
![2021-03-04_14 05 11](https://user-images.githubusercontent.com/40730042/110225238-2c230f00-7ea9-11eb-80b3-b6a6c9767ff0.png)
![2021-03-04_13 59 49](https://user-images.githubusercontent.com/40730042/110225240-2fb69600-7ea9-11eb-8822-89f6f374d4ec.png)

**Comment by MarkusBordihn** [comment]
Unfortunately game rules changes are automatically broadcast to all "op" players, but not to "normal" players.
I will check if I could suppress them somehow but because it's an core behavior it could be that I could not do a lot in this case.
But you can disable the game rule changes over the config, if they are getting to annoying.
