### ISSUE TITLE
Well Idk how to explain this

### ISSUE THREAD

**Issue by ModernGamingWorld** [MarkusBordihn/adaptive_performance_tweaks#11]
Your Mod is causing recipes to stop working on server side, Example below.

If I disable your mod then the recipe works like normal

https://github.com/Brian-Wuest/MC-Prefab/issues/167

**Comment by MarkusBordihn** [comment]
Thanks for the report. Was not really able to reproduce the issue on my side with a fresh installation.

The mod is also not adjusting any GUI related stuff or using any mixin which could explain the issue.
Are you sure that the issue happen with this mod and not some other mod ?

If you are able to reproduce the issue, please set the `logLevel = "debug"` inside the adaptive_performance_tweaks-common.toml config file and share the logfile.

**Comment by ModernGamingWorld** [comment]
Well See, I put your mod in and then the recipe stopped working, but after I disabled your mod the recipe started to work again

**Comment by ModernGamingWorld** [comment]
Really The Only Source I can give ya is using my Custom Modpack of 270 mods running with Java 15, but I removed your mod on my server to stop people crying and as soon as I removed your mod the recipe above was not broken Idk what to tell you, if its not an issue then I will just close this and not use this mod to help on my server

**Comment by MarkusBordihn** [comment]
According your modlist you are using some core mods like performat which could cause such issues.
I will check If I could reproduce the issued with your modpack but its very likely a issue with one of these core mods.

**Comment by MarkusBordihn** [comment]
Ok, I removed some core mods which shows up in the logs and the issue was no longer reprodudible for me.
Which means that this is an issue in combination with one of the coremods and not this mod itself.

![2021-05-14_13 06 18](https://user-images.githubusercontent.com/12183293/118262992-f8222680-b4b5-11eb-8c27-51033b0e18db.png)

Please also check your server.zip file, because I got some virus warnings from this file, see:
https://www.virustotal.com/gui/file/7536ec0c7d15c3a58bc380f30a164c983248c67a37699388420accff20a6f3cb/detection
