### ISSUE TITLE
profiled the mod on a server

### ISSUE THREAD

**Issue by Iacchus-sys** [MarkusBordihn/adaptive_performance_tweaks#20]
Is your feature request related to a problem?
Yes(idk if you call this a problem). i profiled the mod yesterday and found some interesting server thread usage.

Describe the solution you'd like
trying to lower the mods impact on server thread

Describe alternatives you've considered
disable logging in config cause that would kill about 5% or more

Additional context
this is the profile of the server with your mod. its second on the list
https://spark.lucko.me/RmrcsdcLgR
be sure to click view all

hope to hear from you soon!.
would not say this is urgent by any means just want to see if maybe i could give insight in to how the mod preforms on servers(heavily modded server 200+)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. In this case it's expected that the mod is in the top 3 of server thread time, because it's needs to check all spawn events (10-200/secs) depending on the amount of mods) on the server.
If you take a look into the breakdown you will see that only the  Spawn Manager has a higher load, the rest has a lower load.

Thanks a lot for the hint with the logging, seems I need to adjust some debug and trace calls inside the Spawn Manager, because they should not take this high amount of log processing.

**Comment by Iacchus-sys** [comment]
> Thanks a lot for the report. In this case it's expected that the mod is in the top 3 of server thread time, because it's needs to check all spawn events (10-200/secs) depending on the amount of mods) on the server.
> If you take a look into the breakdown you will see that only the Spawn Manager has a higher load, the rest has a lower load.
> 
> Thanks a lot for the hint with the logging, seems I need to adjust some debug and trace calls inside the Spawn Manager, because they should not take this high amount of log processing.

No problem man keep up the good work

**Comment by MarkusBordihn** [comment]
This should be fixed in the next version 1.1.1 which should be live in the next hours.

Version 1.1.0 : https://spark.lucko.me/6jaiOElmVg
Version 1.1.1: https://spark.lucko.me/R3suNbKF56

The fix has improved the performance from about 3-10% server time to only 0.05% - 0.10% server time.
Thanks again for the report so that I'm was able to find and fix this issue.
