### ISSUE TITLE
Crash out of no where

### ISSUE THREAD

**Issue by BugmanBugman** [MarkusBordihn/adaptive_performance_tweaks#6]
**Describe the bug**
No idea as to why this bug happened, I had just spawned into a world and the mod suddenly crashed

**To Reproduce**
1. spawn into world
2. move around for some mobs
3. game crashes

**Expected behavior**
To not crash

**Debugging**
Before reporting a issue please use `/aptweaks debug true` to enable debugging and check if there is anything relevant in the debug.log file.

**Additional context**
https://gist.github.com/BugmanBugman/d2ff34663f2676a8968cce48463025fa

**Comment by MarkusBordihn** [comment]
Thanks for the report. Seems there was an entity in your world without a name which cause this crash.
I added a error check to log a warning in the console instead of crashing, could be it's comming from one of the installed mods.
Normally all entities should have a name which makes this crash a little bit strange.

**Comment by MarkusBordihn** [comment]
Thanks for the note, I will add the same check to the Monster cleanup.
Let me know if you see anything like "Unknown entity name for entity..." in your log to maybe isolate the issue to a specific mod.
